local buf_map = function(bufnr, mode, lhs, rhs, opts)
	vim.api.nvim_buf_set_keymap(bufnr, mode, lhs, rhs, opts or {
		silent = true,
	})
end

require("lspconfig").tsserver.setup({
	-- settings = {documentFormatting = true},
	-- on_attach = function(client, bufnr)
	-- local ts_utils = require("nvim-lsp-ts-utils")
	-- ts_utils.setup({})
	-- ts_utils.setup_client(client)
	-- buf_map(bufnr, "n", "gs", ":TSLspOrganize<CR>")
	-- buf_map(bufnr, "n", "gi", ":TSLspRenameFile<CR>")
	-- buf_map(bufnr, "n", "go", ":TSLspImportAll<CR>")
	-- vim.cmd("command! LspDef lua vim.lsp.buf.definition()")
	-- vim.cmd("command! LspCodeAction lua vim.lsp.buf.code_action()")
	-- vim.cmd("command! LspRangeCodeAction lua vim.lsp.buf.range_code_action()")
	-- vim.cmd("command! LspHover lua vim.lsp.buf.hover()")
	-- vim.cmd("command! LspRename lua vim.lsp.buf.rename()")
	-- vim.cmd("command! LspRefs lua vim.lsp.buf.references()")
	-- vim.cmd("command! LspTypeDef lua vim.lsp.buf.type_definition()")
	-- vim.cmd("command! LspImplementation lua vim.lsp.buf.implementation()")
	-- vim.cmd("command! LspDiagPrev lua vim.diagnostic.goto_prev()")
	-- vim.cmd("command! LspDiagNext lua vim.diagnostic.goto_next()")
	-- vim.cmd("command! LspDiagLine lua vim.diagnostic.open_float()")
	-- vim.cmd("command! LspSignatureHelp lua vim.lsp.buf.signature_help()")
	-- buf_map(bufnr, "n", "gd", ":LspDef<CR>")
	-- buf_map(bufnr, "n", "gr", ":LspRename<CR>")
	-- buf_map(bufnr, "n", "gy", ":LspTypeDef<CR>")
	-- buf_map(bufnr, "n", "K", ":LspHover<CR>")
	-- buf_map(bufnr, "n", "[a", ":LspDiagPrev<CR>")
	-- buf_map(bufnr, "n", "]a", ":LspDiagNext<CR>")
	-- buf_map(bufnr, "n", "<leader>ca", ":LspCodeAction<CR>")
	-- buf_map(bufnr, "n", "<leader>cra", ":LspRangeCodeAction<CR>")
	-- buf_map(bufnr, "n", "<Leader>a", ":LspDiagLine<CR>")
	-- buf_map(bufnr, "i", "<C-x><C-x>", "<cmd> LspSignatureHelp<CR>")
	-- vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.format({ async = false })")
	-- vim.cmd("command! LspFormatting lua vim.lsp.buf.format({ async = true })")
	-- end,
})
